# Generated by Django 5.2.3 on 2025-06-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='response_type',
            field=models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text')], default='text', max_length=4),
        ),
        migrations.AlterField(
            model_name='commands',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='serial',
            field=models.IntegerField(default=1),
        ),
    ]
