# Generated by Django 5.2.3 on 2025-06-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commands_response_type_alter_commands_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='forwhat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
